### ISSUE TITLE
Example won't run

### ISSUE THREAD

**Issue by andrekovac** [octavioturra/react-native-alt-beacon#5]
When running `react-native run-android` after `npm install` in the example\ folder after cloning the rep, I get the following error:

```
Android project not found. Maybe run react-native android first?
```

When pulling the project from npm, the src/ folder in the example/ folder is not consistent with the repo here on Github. For example the files Button.js and List.js are missing.

That might be related to the npm difficulties you mentioned in issue #4 .

**Comment by octavioturra** [comment]
Sorry, I've ignored the gradle project file. 
I think that it's ok now.

But the npm is an issue that is giving me headaches. 
I'm waiting for the response from npm team.
